#!/usr/bin/env php
<?php
require __DIR__ . '/vendor/autoload.php';
use Symfony\Component\Console\Application;
use Dotenv\Dotenv;
$dotenv = Dotenv::createImmutable(__DIR__);
$dotenv->load();

require_once __DIR__ . '/commands/SetupCommand.php';
require_once __DIR__ . '/commands/MigrationCommand.php';
require_once __DIR__ . '/commands/ModelCommand.php';
require_once __DIR__ . '/commands/ControllerCommand.php';
require_once __DIR__ . '/commands/MigrateCommand.php';
require_once __DIR__ . '/commands/WebCommand.php';
require_once __DIR__ . '/commands/HooksCommand.php';

$app = new Application('WHMCS Addon Framework', '1.0.0');
$app->add(new SetupCommand());
$app->add(new MigrationCommand());
$app->add(new ModelCommand()); 
$app->add(new ControllerCommand());
$app->add(new MigrateCommand());
$app->add(new HooksCommand());
$app->add(new WebCommand());

$app->run();




